"""
markdown_export.py — Export current ledger state to Markdown.
Designed to fit a git-based workflow: commit after each scenario step.
"""
from pathlib import Path
from datetime import datetime
from ledger import Ledger, Entity

OUTPUT_FILE = Path("balancesheets.md")


def entity_to_md(entity: Entity) -> str:
    lines = [f"### {entity.name}\n"]
    lines.append("| Assets | Liabilities & Equity |")
    lines.append("|--------|----------------------|")

    assets = entity.assets
    liabs = entity.liabilities
    max_rows = max(len(assets), len(liabs), 1)

    for i in range(max_rows):
        a_cell = ""
        l_cell = ""
        if i < len(assets):
            a = assets[i]
            suffix = f" ← {a['counterparty']}" if a.get("counterparty") else ""
            a_cell = f"{a['label']} {a['amount']:,.0f}{suffix}"
        if i < len(liabs):
            l = liabs[i]
            suffix = f" → {l['counterparty']}" if l.get("counterparty") else ""
            l_cell = f"{l['label']} {l['amount']:,.0f}{suffix}"
        lines.append(f"| {a_cell} | {l_cell} |")

    # Totals
    balanced = entity.is_balanced()
    bal_note = "✓" if balanced else "⚠️ UNBALANCED"
    lines.append(f"| **TOTAL {entity.total_assets():,.0f}** | **TOTAL {entity.total_liabilities():,.0f}** {bal_note} |")
    return "\n".join(lines)


def graph_to_md(ledger: Ledger) -> str:
    if not ledger.transactions:
        return "_No transactions yet._"

    lines = ["```"]
    seen = set()
    graph: dict[str, dict] = {}
    for tx in ledger.transactions:
        s, r = tx["sender"], tx["receiver"]
        if s not in graph:
            graph[s] = {}
        if r not in graph[s]:
            graph[s][r] = []
        graph[s][r].append((tx["instrument"], tx["amount"]))

    for sender, targets in graph.items():
        for receiver, flows in targets.items():
            for instrument, amount in flows:
                lines.append(f"{sender} --[{instrument} {amount:,.0f}]--> {receiver}")

    lines.append("```")
    return "\n".join(lines)


def export(ledger: Ledger, append: bool = True):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sections = [f"## Balance Sheets — {timestamp}\n"]

    for entity in ledger.entities.values():
        sections.append(entity_to_md(entity))
        sections.append("")

    sections.append("### Payment Flow\n")
    sections.append(graph_to_md(ledger))
    sections.append("\n---\n")

    content = "\n".join(sections)

    if append and OUTPUT_FILE.exists():
        OUTPUT_FILE.write_text(OUTPUT_FILE.read_text(encoding="utf-8") + "\n" + content, encoding="utf-8")
    else:
        header = "# T-Accounts Ledger\n\n_Generated by taccounts CLI_\n\n---\n\n"
        OUTPUT_FILE.write_text(header + content, encoding="utf-8")

    return OUTPUT_FILE
